# SPDX-FileCopyrightText: 2025 MiromindAI
#
# SPDX-License-Identifier: Apache-2.0

"""
Unit tests for FallbackFinalAnswerGenerator.

These tests exercise the fallback logic without making real LLM calls.
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from miroflow.agents.context import AgentContext
from miroflow.io_processor.fallback_final_answer_generator import (
    FallbackFinalAnswerGenerator,
    _PLACEHOLDER_ANSWERS,
    _clean_llm_response,
)
from miroflow.llm.base import ContextLimitError


# ---------------------------------------------------------------------------
# Helper: build a minimal FallbackFinalAnswerGenerator without framework init
# ---------------------------------------------------------------------------

def _make_processor(b_response: str | None = "B-style answer", a_response: str | None = None):
    """Return a FallbackFinalAnswerGenerator with mocked llm_client and prompt_manager."""
    proc = object.__new__(FallbackFinalAnswerGenerator)

    # Mock prompt_manager
    pm = MagicMock()
    pm.render_prompt = MagicMock(return_value="summarise please")
    proc.prompt_manager = pm

    # Mock llm_client – returns b_response for first call, a_response for second
    llm = MagicMock()
    responses = []
    if b_response is not None:
        mock_b = MagicMock()
        mock_b.response_text = b_response
        responses.append(mock_b)
    if a_response is not None:
        mock_a = MagicMock()
        mock_a.response_text = a_response
        responses.append(mock_a)

    llm.create_message = AsyncMock(side_effect=responses if responses else [MagicMock(response_text="")])
    proc.llm_client = llm

    return proc


def _make_ctx(**kwargs) -> AgentContext:
    return AgentContext(**kwargs)


# ---------------------------------------------------------------------------
# _clean_llm_response helper
# ---------------------------------------------------------------------------

class TestCleanLlmResponse:
    def test_empty_string(self):
        assert _clean_llm_response("") == ""

    def test_removes_think_blocks(self):
        text = "<think>inner thoughts</think>\n\nActual answer here."
        assert _clean_llm_response(text) == "Actual answer here."

    def test_removes_multiple_think_blocks(self):
        text = "<think>a</think>\n<think>b</think>\nResult"
        assert _clean_llm_response(text) == "Result"

    def test_removes_tool_call(self):
        text = "Some content\n<use_mcp_tool>tool call</use_mcp_tool>"
        assert "use_mcp_tool" not in _clean_llm_response(text)

    def test_removes_empty_boxed(self):
        text = r"Answer: \boxed{} is empty"
        result = _clean_llm_response(text)
        assert r"\boxed{}" not in result

    def test_plain_text_unchanged(self):
        text = "This is a plain answer."
        assert _clean_llm_response(text) == text


# ---------------------------------------------------------------------------
# _has_valid_answer
# ---------------------------------------------------------------------------

class TestHasValidAnswer:
    def test_empty_final_boxed(self):
        ctx = _make_ctx(final_boxed_answer="", llm_extracted_final_answer="")
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False

    def test_none_final_boxed(self):
        ctx = _make_ctx(final_boxed_answer=None, llm_extracted_final_answer=None)
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False

    def test_placeholder_no_final_answer(self):
        ctx = _make_ctx(
            final_boxed_answer="No final answer generated.",
            llm_extracted_final_answer="",
        )
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False

    def test_placeholder_no_boxed_content(self):
        ctx = _make_ctx(
            final_boxed_answer="Final response is generated by LLM, but no \\boxed{} content found.",
            llm_extracted_final_answer="",
        )
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False

    def test_valid_final_boxed(self):
        ctx = _make_ctx(final_boxed_answer="42", llm_extracted_final_answer="")
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is True

    def test_valid_llm_extracted_without_boxed_is_not_valid(self):
        # llm_extracted_final_answer alone is no longer sufficient; only
        # final_boxed_answer is authoritative.  An non-empty llm_extracted value
        # with an empty/placeholder final_boxed should still trigger the fallback.
        ctx = _make_ctx(final_boxed_answer="", llm_extracted_final_answer="Paris")
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False

    def test_both_valid_returns_true(self):
        # When final_boxed_answer is a real answer, it is valid regardless of
        # what llm_extracted_final_answer contains.
        ctx = _make_ctx(final_boxed_answer="42", llm_extracted_final_answer="forty-two")
        assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is True


# ---------------------------------------------------------------------------
# run_internal – no-op when valid answer already present
# ---------------------------------------------------------------------------

class TestRunInternalNoop:
    @pytest.mark.asyncio
    async def test_skips_when_valid_final_boxed(self):
        proc = _make_processor()
        ctx = _make_ctx(
            final_boxed_answer="correct answer",
            llm_extracted_final_answer="",
            message_history=[],
        )
        result = await proc.run_internal(ctx)
        # LLM should NOT be called
        proc.llm_client.create_message.assert_not_called()
        # Result AgentContext should be empty (no overrides)
        assert result.get("final_boxed_answer", None) is None

    @pytest.mark.asyncio
    async def test_runs_when_only_llm_extracted_set(self):
        # Previously the fallback was skipped when llm_extracted_final_answer was
        # non-empty even with a placeholder final_boxed_answer.  Now it must run.
        proc = _make_processor(b_response="Fallback answer for incomplete task")
        ctx = _make_ctx(
            final_boxed_answer="No final answer generated.",
            llm_extracted_final_answer="Some non-empty LLM explanation text",
            task_description="What is the capital of France?",
            message_history=[{"role": "assistant", "content": "I searched but ran out of turns"}],
        )
        result = await proc.run_internal(ctx)
        # B-style fallback must have run and produced output
        proc.llm_client.create_message.assert_called_once()
        assert result.get("final_boxed_answer") == "Fallback answer for incomplete task"


# ---------------------------------------------------------------------------
# run_internal – B-style fallback triggered
# ---------------------------------------------------------------------------

class TestRunInternalBStyle:
    @pytest.mark.asyncio
    async def test_b_style_writes_final_boxed(self):
        proc = _make_processor(b_response="## Final Answer\n\nThe answer is 42.")
        ctx = _make_ctx(
            final_boxed_answer="No final answer generated.",
            llm_extracted_final_answer="",
            task_description="What is 6*7?",
            message_history=[{"role": "assistant", "content": "6 * 7 = 42"}],
        )
        result = await proc.run_internal(ctx)

        # B-style: result should be written to final_boxed_answer
        assert result.get("final_boxed_answer") == "## Final Answer\n\nThe answer is 42."
        assert result.get("llm_extracted_final_answer") == "## Final Answer\n\nThe answer is 42."

    @pytest.mark.asyncio
    async def test_think_blocks_stripped_from_b_response(self):
        raw = "<think>inner</think>\n\nThe answer is Paris."
        proc = _make_processor(b_response=raw)
        ctx = _make_ctx(
            final_boxed_answer="",
            llm_extracted_final_answer="",
            task_description="Capital of France?",
            message_history=[],
        )
        result = await proc.run_internal(ctx)
        # think block should be removed
        assert "<think>" not in result.get("final_boxed_answer", "")
        assert "The answer is Paris." in result.get("final_boxed_answer", "")

    @pytest.mark.asyncio
    async def test_trailing_user_message_removed_before_call(self):
        proc = _make_processor(b_response="Fallback answer")
        ctx = _make_ctx(
            final_boxed_answer="",
            llm_extracted_final_answer="",
            task_description="Q?",
            message_history=[
                {"role": "assistant", "content": "Some response"},
                {"role": "user", "content": "Follow-up question"},
            ],
        )
        await proc.run_internal(ctx)

        # Check the messages passed to LLM - user's trailing message should be removed
        call_args = proc.llm_client.create_message.call_args
        if call_args.args:
            sent_history = call_args.args[0]
        else:
            sent_history = call_args.kwargs["message_history"]

        user_followup = [
            m for m in sent_history
            if m.get("role") == "user" and "Follow-up" in str(m.get("content", ""))
        ]
        assert len(user_followup) == 0


# ---------------------------------------------------------------------------
# run_internal – A-style fallback when B fails
# ---------------------------------------------------------------------------

class TestRunInternalAStyleFallback:
    @pytest.mark.asyncio
    async def test_a_style_when_b_returns_empty(self):
        proc = object.__new__(FallbackFinalAnswerGenerator)
        pm = MagicMock()
        pm.render_prompt = MagicMock(return_value="summarise please")
        proc.prompt_manager = pm

        llm = MagicMock()
        # First call (B-style) returns empty; second call (A-style) returns content
        empty_resp = MagicMock()
        empty_resp.response_text = ""
        a_resp = MagicMock()
        a_resp.response_text = "Failure type: incomplete\nWhat happened: ran out of turns"
        llm.create_message = AsyncMock(side_effect=[empty_resp, a_resp])
        proc.llm_client = llm

        ctx = _make_ctx(
            final_boxed_answer="",
            llm_extracted_final_answer="",
            task_description="Some task",
            message_history=[],
        )
        result = await proc.run_internal(ctx)

        # A-style result should be written to summary as well
        assert result.get("summary") is not None
        assert result.get("final_boxed_answer") is not None

    @pytest.mark.asyncio
    async def test_a_style_when_b_raises_context_limit(self):
        proc = object.__new__(FallbackFinalAnswerGenerator)
        pm = MagicMock()
        pm.render_prompt = MagicMock(return_value="prompt")
        proc.prompt_manager = pm

        llm = MagicMock()
        a_resp = MagicMock()
        a_resp.response_text = "Failure type: blocked\nWhat happened: context limit"
        llm.create_message = AsyncMock(side_effect=[ContextLimitError("too long"), a_resp])
        proc.llm_client = llm

        ctx = _make_ctx(
            final_boxed_answer="",
            llm_extracted_final_answer="",
            task_description="Some task",
            message_history=[{"role": "assistant", "content": "some content"}],
        )
        result = await proc.run_internal(ctx)

        # Should fall through to A-style
        assert result.get("final_boxed_answer") is not None or result.get("summary") is not None

    @pytest.mark.asyncio
    async def test_context_limit_in_a_style_returns_static_message(self):
        proc = object.__new__(FallbackFinalAnswerGenerator)
        pm = MagicMock()
        pm.render_prompt = MagicMock(return_value="prompt")
        proc.prompt_manager = pm

        llm = MagicMock()
        # Both B-style and A-style raise ContextLimitError
        llm.create_message = AsyncMock(
            side_effect=[ContextLimitError("too long"), ContextLimitError("too long")]
        )
        proc.llm_client = llm

        ctx = _make_ctx(
            final_boxed_answer="",
            llm_extracted_final_answer="",
            task_description="Some task",
            message_history=[],
        )
        result = await proc.run_internal(ctx)

        # A-style ContextLimitError produces a static message
        final = result.get("final_boxed_answer") or result.get("summary") or ""
        assert "context" in final.lower() or "limit" in final.lower()


# ---------------------------------------------------------------------------
# Placeholder answers coverage
# ---------------------------------------------------------------------------

class TestPlaceholderAnswers:
    def test_all_placeholders_recognized(self):
        for placeholder in _PLACEHOLDER_ANSWERS:
            ctx = _make_ctx(
                final_boxed_answer=placeholder,
                llm_extracted_final_answer="",
            )
            assert FallbackFinalAnswerGenerator._has_valid_answer(ctx) is False
